name: CI Build

on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Get Version
        run: VERSION=$(cat version.txt)

      # TODO: Check version is used.

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: edufolly
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Build & Push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: Dockerfile
          tags: |
            edufolly/sshd-container:$VERSION
            edufolly/sshd-container:latest
