name: CI Build

on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install sshpass
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update -y
          sudo apt-get install jq -y

      - name: Get Version
        run: |
          VERSION=$(grep 'version:' version.yaml | cut -c 10-)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check version is used.
        run: |
          URL=https://api.github.com/repos/edufolly/sshd-container/releases/latest
          LATEST=$(curl --silent "$URL" | jq -r .name)
          if [ "$LATEST" == "v$VERSION" ]; then
            echo "Version is used."
            exit 1
          fi

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: edufolly
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Build & Push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: Dockerfile
          tags: |
            edufolly/sshd-container:${{ env.VERSION }}
            edufolly/sshd-container:latest

      - name: Creating GitHub Tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{ env.VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
