name: Pull Request Tests

on: [pull_request]

jobs:
  #########
  # Tests #
  #########
  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install sshpass
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update -y
          sudo apt-get install sshpass -y

      - name: Running Tests
        run: ./test.sh
